<?
/*
function mod_test3_init()
{
	//drupal_set_message("function mod_test3_init !!!");

	$global_fs_root_src = "";
	variable_set($global_fs_root_src, '/mnt/transcend/0_sites/book_history_engraving/sites/default/files');

	$global_fs_root_dest = "";
	variable_set($global_fs_root_dest, '/mnt/wd160/documents/0_sites/site_graphics');
}
*/
function mod_test3_help ($path, $arg)
{
    $output = '';
    switch ($path)
     {
        case "admin/help#mod_test3":
    	    $output = '<p>'.t("Test3 help").'</p>';
    	    break;
     }
     return $output;
} 
//=============== end function

function mod_test3_perm ()
{
    return array ('access mod_test3 content','access admins page');
} 
//=============== end function


function mod_test3_menu ()
{
    $items = array();
/*
    $items['admin/settings/mod_test3'] = array(
     'title' => 'test3 module settings',
     'description' => 'Description of your settings page test3',
     'page callback' => 'drupal_get_form',// создание формы
     'page arguments' => array ('mod_test3_admin'),	// вызов функции 
     'access arguments' => array ('access administration pages'),
     'type' => MENU_NORMAL_ITEM,
    );
*/
    $items['mod_test3'] = array(
    'title' => 'Тест 3',	//Заголовок страницы
    'page callback' => 'drupal_get_form',// создание формы
    'page arguments' => array('mod_test3_form'),// вызов функции 
    'access arguments' => array('access mod_test3 content')
    );
                                        
    return $items;
}
//================= end function

//===========================
//
//===========================
function mod_test3_form ($form_state)
{
	drupal_set_message("function mod_test3_form");

	$form = array();
	$form['mod_test3_wrapper'] = array(
		'#prefix' => '<div style="background:palegreen;">',
		'#value' => t('test value'),
		'#suffix' => '</div>',
	);
	return $form;
}
//================= end function

//===========================
//
//===========================
function mod_test3_admin ()
{
    $form = array();
    
    $form['sitename'] = array(
        '#type' => 'textfield',
        '#title' => t('Site'),
        '#default_value' => variable_get('sitename',''),
        '#size' => 20,
        '#maxlength' => 20,
        '#description' => t('withoutt "http://"'),
    );

    return system_settings_form ($form);
}
//========================= end function


//===========================
//
//===========================
function mod_test3_block ()
{
        
}
//=============== end function

//===========================
// Фильтрация текста
// Implementation of hook_filter().
//===========================
function mod_test3_filter_info() {

	//drupal_set_message("function mod_test3_filter_info()");

  $filters['filter_name'] = array(
    'title' => t('engrave book text filter'),
    'process callback' => 'mod_test3_filter_process',
  );

  return $filters;
}
//=============== end function

//===========================
// filter process callback.
//===========================
function mod_test3_filter_process($text, $filter, $format) {

	//drupal_set_message("function mod_test3_filter_process");

  //$output = preg_replace('/[/term]/', '<b>/term</b>', $text);
  //$output = preg_replace('/[term]/', '<b>term</b>', $text);

	$text = str_replace('[notes]', '<span class="notes">', $text);
	$text = str_replace('[/notes]', '</span>', $text);

	$text = str_replace('[picture_text]', '<span class="picture_text">', $text);
	$text = str_replace('[/picture_text]', '</span>', $text);

	$text = str_replace('[name]', '<span class="name">', $text);
	$text = str_replace('[/name]', '</span>', $text);

	$text = str_replace('[term]', '<span class="termin">', $text);
	$output = str_replace('[/term]', '</span>', $text);

  return $output;
}

//=============== end function

?>
