BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `field_data_field_related_links` (
	`entity_type`	VARCHAR ( 128 ) NOT NULL DEFAULT '',
	`bundle`	VARCHAR ( 128 ) NOT NULL DEFAULT '',
	`deleted`	INTEGER NOT NULL DEFAULT 0,
	`entity_id`	INTEGER NOT NULL CHECK(entity_id >= 0),
	`revision_id`	INTEGER DEFAULT NULL CHECK(revision_id >= 0),
	`language`	VARCHAR ( 32 ) NOT NULL DEFAULT '',
	`delta`	INTEGER NOT NULL CHECK(delta >= 0),
	`field_related_links_value`	VARCHAR ( 255 ) DEFAULT NULL,
	`field_related_links_format`	VARCHAR ( 255 ) DEFAULT NULL,
	PRIMARY KEY(`entity_type`,`entity_id`,`deleted`,`delta`,`language`)
);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,162,162,'und',0,'<a data-type="playlist-file" href="/music/0_playlists/Rowan.json">Rowan.json</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,164,164,'und',0,'<a data-type="playlist-file" href="/music/0_playlists/My dying bride.json">My dying bride.json</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,166,166,'und',0,'<a data-type="playlist-file" href="/music/0_playlists/Manowar.json">Manowar.json</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,169,169,'und',0,'<a data-type="playlist-file" href="/music/0_playlists/russian.json">russian.json</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,172,172,'und',0,'<a data-type="playlist-file" href="/music/0_playlists/punk, hardcore.json">punk, hardcore.json</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,173,173,'und',0,'<a data-type="external-link" href="https://music.yandex.ru/users/roman-laptev/playlists/1010">music.yandex.ru</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,173,173,'und',1,'<a data-type="playlist-file" href="/music/0_playlists/rus_punk.json">rus_punk.json</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,174,174,'und',0,'<a data-type="external-link" href="https://music.yandex.ru/users/roman-laptev/playlists/1006">music.yandex.ru</a>
',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,174,174,'und',1,'<a data-type="playlist-file" href="/music/0_playlists/GrOb.json">GrOb.json</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,175,175,'und',0,'<a data-type="external-link" href="https://music.yandex.ru/users/roman-laptev/playlists/1012">music.yandex.ru</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,175,175,'und',1,'<a data-type="playlist-file" href="/music/0_playlists/ska.json">ska.json</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,176,176,'und',0,'<a data-type="playlist-file" href="/music/0_playlists/thrash, death, grindecore, hardcore.json">thrash, death, grindecore, hardcore.json</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,179,179,'und',0,'<a data-type="playlist-file" href="/music/0_playlists/red_elvices.json">red_elvices.json</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,180,180,'und',0,'<a data-type="playlist-file" href="/music/0_playlists/disko, pop.json">disko, pop.json</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,155,155,'und',0,'<a data-type="external-link" href="https://music.yandex.ru/users/roman-laptev/playlists/1021">music.yandex.ru</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,155,155,'und',1,'<a data-type="playlist-file" href="/music/0_playlists/Jazz and swing.json">Jazz and swing.json</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,187,187,'und',0,'<a data-type="playlist-file" href="/music/0_playlists/mix_transe, hip-hop, latin.json">mix_transe, hip-hop, latin.json</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,167,167,'und',0,'<a data-type="external-link" href="https://music.yandex.ru/users/roman-laptev/playlists/1016">music.yandex.ru</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,167,167,'und',1,'<a data-type="playlist-file" href="/music/0_playlists/Therion.json">Therion.json</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,168,168,'und',0,'<a data-type="external-link" href="https://music.yandex.ru/users/roman-laptev/playlists/1015">music.yandex.ru</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,168,168,'und',1,'<a data-type="playlist-file" href="/music/0_playlists/Nightwish.json">Nightwish.json</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,183,183,'und',0,'<a data-type="playlist-file" href="/music/0_playlists/indian.json">indian.json</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,157,157,'und',0,'<a data-type="external-link" href="https://music.yandex.ru/users/roman-laptev/playlists/1007">music.yandex.ru</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,157,157,'und',1,'<a data-type="external-link" href="https://www.youtube.com/watch?v=7lC1lRz5Z_s&list=PL2sTusldk6UjU_GTUOs17hBo_pVe1ZauI">youtube</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,157,157,'und',2,'<a data-type="playlist-file" href="/music/0_playlists/Vivaldi.json">Vivaldi.json</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,159,159,'und',0,'<a data-type="external-link" href="https://music.yandex.ru/users/roman-laptev/playlists/1007">music.yandex.ru</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,159,159,'und',1,'<a data-type="external-link" href="https://www.youtube.com/watch?v=7lC1lRz5Z_s&list=PL2sTusldk6UjU_GTUOs17hBo_pVe1ZauI">youtube</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,159,159,'und',2,'<a data-type="playlist-file" href="/music/0_playlists/Bach.json">Bach.json</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,158,158,'und',0,'<a data-type="external-link" href="https://music.yandex.ru/users/roman-laptev/playlists/1007">music.yandex.ru</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,158,158,'und',1,'<a data-type="external-link" href="https://www.youtube.com/watch?v=7lC1lRz5Z_s&list=PL2sTusldk6UjU_GTUOs17hBo_pVe1ZauI">youtube</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,158,158,'und',2,'<a data-type="playlist-file" href="/music/0_playlists/Mozart.json">Mozart.json</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,160,160,'und',0,'<a data-type="external-link" href="https://music.yandex.ru/users/roman-laptev/playlists/1007">music.yandex.ru</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,160,160,'und',1,'<a data-type="external-link" href="https://www.youtube.com/watch?v=7lC1lRz5Z_s&list=PL2sTusldk6UjU_GTUOs17hBo_pVe1ZauI">youtube</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,160,160,'und',2,'<a data-type="playlist-file" href="/music/0_playlists/Handel.json">Handel.json</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,171,171,'und',0,'<a data-type="external-link" href="https://music.yandex.ru/users/roman-laptev/playlists/1020">music.yandex.ru</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,171,171,'und',1,'<a data-type="playlist-file" href="/music/0_playlists/KSU.json">KSU.json</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,170,170,'und',0,'<a data-type="playlist-file" href="/music/0_playlists/Kreator.json">Kreator.json</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,163,163,'und',0,'<a data-type="external-link" href="https://music.yandex.ru/users/roman-laptev/playlists/1017">music.yandex.ru</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,163,163,'und',1,'<a data-type="playlist-file" href="/music/0_playlists/judas_priest.json">judas_priest.json</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,181,181,'und',0,'<a data-type="external-link" href="https://www.youtube.com/playlist?list=PL2sTusldk6UhJ9XXBSCA5Kb-r4e3q0qt4">music - medieval, church, youtube</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,181,181,'und',1,'<a data-type="playlist-file" href="/music/0_playlists/folk, chants.json">folk, chants.json</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,182,182,'und',0,'<a data-type="external-link" href="https://music.yandex.ru/users/roman-laptev/playlists/1004">music.yandex.ru</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,182,182,'und',1,'<a data-type="playlist-file" href="/music/0_playlists/heavy,speed,power.json">heavy,speed,power.json</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,185,185,'und',0,'<a data-type="playlist-file" href="/music/0_playlists/apocalyptica.json">apocalyptica.json</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,188,188,'und',0,'<a data-type="playlist-file" href="/music/0_playlists/rock.json">rock.json</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,184,184,'und',0,'<a data-type="playlist-file" href="/music/0_playlists/melodic, folk metal.json">melodic, folk metal.json</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,186,186,'und',0,'<a data-type="playlist-file" href="/music/0_playlists/Korpiklaani.json">Korpiklaani.json</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,156,156,'und',0,'<a data-type="playlist-file" href="/music/0_playlists/blues, rock_n_roll, swing, jazz.json">blues, rock_n_roll, swing, jazz.json</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,177,177,'und',0,'<a data-type="playlist-file" href="/music/0_playlists/trance, rave, hip-hop, electronic.json">trance, rave, hip-hop, electronic.json</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,161,161,'und',0,'<a data-type="external-link" href="https://music.yandex.ru/users/roman-laptev/playlists/1007">music.yandex.ru</a>
',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,161,161,'und',1,'<a data-type="playlist-file" href="/music/0_playlists/classic.json">classic.json</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,165,165,'und',0,'<a data-type="playlist-file" href="/music/0_playlists/Master.json">Master.json</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,110,110,'und',0,'<a data-type="external-link" href="https://music.yandex.ru/users/roman-laptev/playlists/1019" class="btn btn-info" target="_blank">yandex music</a>',NULL);
INSERT INTO `field_data_field_related_links` (entity_type,bundle,deleted,entity_id,revision_id,language,delta,field_related_links_value,field_related_links_format) VALUES ('node','playlist',0,110,110,'und',1,'<a data-type="playlist-file" href="/music/0_playlists/metallica.json">metallica.json</a>',NULL);
CREATE INDEX IF NOT EXISTS `field_data_field_related_links_revision_id` ON `field_data_field_related_links` (
	`revision_id`
);
CREATE INDEX IF NOT EXISTS `field_data_field_related_links_language` ON `field_data_field_related_links` (
	`language`
);
CREATE INDEX IF NOT EXISTS `field_data_field_related_links_field_related_links_format` ON `field_data_field_related_links` (
	`field_related_links_format`
);
CREATE INDEX IF NOT EXISTS `field_data_field_related_links_entity_type` ON `field_data_field_related_links` (
	`entity_type`
);
CREATE INDEX IF NOT EXISTS `field_data_field_related_links_entity_id` ON `field_data_field_related_links` (
	`entity_id`
);
CREATE INDEX IF NOT EXISTS `field_data_field_related_links_deleted` ON `field_data_field_related_links` (
	`deleted`
);
CREATE INDEX IF NOT EXISTS `field_data_field_related_links_bundle` ON `field_data_field_related_links` (
	`bundle`
);
COMMIT;
